- hosts: all
  become: True
  tasks:
          - name: reusing ansible tasks
            debug:
                    msg: reusing ansible tasks

          - name: import task to install docker
            import_tasks: task_docker.yml

          - name: import task to install pip
            import_tasks: task_pip.yml



        


